source ${VIRTUALENV_PATH}/bin/activate
echo ""
echo "-----------------------------------------"
echo "Welcome to DebLatex."
echo "-----------------------------------------"
echo ""
echo "- User $(whoami) [$(id -u $USER)] | Group: $(id -g -n) [$(id -g)]"
echo "- HOME:               ${HOME}"
echo "- WORKDIR:            ${WORKDIR}"
echo ""
